name: CI & SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build-and-analyze:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: [17,25]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'

      - name: Start X virtual framebuffer
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1920x1080x24 &>/dev/null &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Maven Clean compile
        run: mvn -B clean compile

    
      # - name: Publish Test Report (JDK ${{ matrix.java-version }}, OS ${{ matrix.os }})
      #   uses: dorny/test-reporter@v1
      #   if: always()
      #   with:
      #     name: Maven Surefire Tests (JDK ${{ matrix.java-version }}, OS ${{ matrix.os }})
      #     path: target/surefire-reports/*.xml
      #     reporter: java-junit

      # - name: SonarCloud Scan
      #   if: matrix.java-version == '17' && matrix.os == 'ubuntu-latest'
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   run: >
      #     mvn -B sonar:sonar
      #     -Dsonar.projectKey=luciasoyyoo_lab-dht-bicam-cabrera
      #     -Dsonar.organization=luciasoyyoo
      #     -Dsonar.host.url=https://sonarcloud.io
      #     -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
